# Generated by Django 4.2.23 on 2025-12-03 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rform',
            name='file',
            field=models.FileField(null=True, upload_to='User_image/'),
        ),
        migrations.AlterField(
            model_name='rform',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
