# Generated by Django 4.2.23 on 2025-12-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_rform_file_alter_rform_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rform',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='User_image/'),
        ),
    ]
